### ISSUE TITLE
if I change mysql service name, cakephp does not find service any more

### ISSUE THREAD

**Issue by mikk150** [openshift/cakephp-ex#71]
when creating cakephp application from example, then pre-hook throws this:
```
Generating Schema...
Error: Database connection "Mysql" is missing, or could not be created.
#0 /opt/app-root/src/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /opt/app-root/src/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/app-root/src/lib/Cake/Model/CakeSchema.php(201): ConnectionManager::getDataSource('default')
#3 /opt/app-root/src/lib/Cake/Console/Command/SchemaShell.php(148): CakeSchema->read(Array)
#4 /opt/app-root/src/lib/Cake/Console/Shell.php(458): SchemaShell->generate()
#5 /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('generate', Array)
#6 /opt/app-root/src/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /opt/app-root/src/app/Console/cake.php(47): ShellDispatcher::run(Array)
#8 {main}
```

**Comment by mikk150** [comment]
ok, db service name cannot contain "-"

**Comment by bparees** [comment]
thanks for the update.

**Comment by mikk150** [comment]
I do not think, that this should be closed, as this should be validated
